version: '3.5'
services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: homework
      POSTGRES_DB: home_db
