# Generated by Django 4.2.3 on 2023-07-04 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('expir_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('user_id', models.UUIDField(default=uuid.UUID('149239d6-f975-4784-913a-bbfc5681bb5a'))),
                ('status', models.CharField(default='new', max_length=50)),
            ],
        ),
    ]
