# Generated by Django 4.2.3 on 2023-07-05 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('a6a227ad-2354-44a9-8989-f3d4e8b90196')),
        ),
    ]
