# Generated by Django 4.2.3 on 2023-07-13 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_number_alter_card_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4f866721-4b51-4aab-a02a-8c5b4b97984f')),
        ),
    ]
