# Generated by Django 4.2.3 on 2023-07-20 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_owner_alter_card_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('69be3e8f-34ef-40f3-aee1-0e2280c62dc1')),
        ),
    ]
