# Generated by Django 4.2.3 on 2023-07-20 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_name_alter_card_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4e1b0f04-b365-45ae-a0c0-02eded904c32')),
        ),
    ]
