# Generated by Django 4.2.3 on 2023-07-20 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_name_alter_card_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('1b545ac2-65f8-4ff4-966d-bc705d017ff1')),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.status'),
        ),
    ]
